import './globals.css'
import type { Metadata } from 'next'
import { } from 'next/font/google'

// const inter = Noto_Serif_Vithkuqi({
//   weight: '400',
//   subsets: ['latin']
// })

export const metadata: Metadata = {
  title: 'Beranda',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-[#DDE6ED] `}>
        {children}
      </body>
    </html>
  )
}
