import type { Metadata } from 'next'
import Navigation from '../components/Navigation';
import ProtectedLayout from './ProtectedLayout';
import Sidebar from '../components/sidebar/Sidebar';


export const metadata: Metadata = {
  title: 'admin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {

  return (
    <section className='h-screen white flex flex-col'>
      <Navigation />
      <div className='flex h-full'>
        <Sidebar />
        <div className='w-full p-10 white'>
          <ProtectedLayout>
            {children}
          </ProtectedLayout>
        </div>
      </div>
    </section>
  )
}
